### ISSUE TITLE
Publication/Peer Review?

### ISSUE THREAD

**Issue by thesofakillers** [jinlanfu/Polyglot_Prompt#1]
Hi cool work!

Do you have any plans to publish it under peer-review? I was only able to find a preprint version.

Thanks!

**Comment by jinlanfu** [comment]
Hi, thanks for your attention to our work. It's still under review, but the arXiv version has been pretty complete, so feel free to check it out.

**Comment by thesofakillers** [comment]
Understood, good luck!
